### ISSUE TITLE
watch scene items rather than scenes?

### ISSUE THREAD

**Issue by alexdean** [lebaston100/OBSliveTally#3]
our live broadcasts use a single camera in a number of different scenes. some are just the camera input, and some are the camera overlaid with still images or text.

i'm having trouble using OBSliveTally in this situation, because i have to pick a single scene to watch. i'd like to be able to pick a scene item to follow insteadl.

i'm wondering what you would think of changing the code so that we can pick a single scene item to watch, and change the tally indicator for any scene which contains that item. i think the needed data is already in the OBS websocket protocol to do this.

**Comment by lebaston100** [comment]
This is actually something that has been planned for a long time but always got put on the backburner.
The concept would be to get a list of all scences, from there get all the sources(which is already there), then make an array out of the scenes that contain that source and basically just watch for that array of scene names.
I'll get right onto it.

**Comment by alexdean** [comment]
that's what Saturdays are for, right? i'm poking at this right now & it seems to be going well. will send you a PR soon.

**Comment by lebaston100** [comment]
i'm bascially done, even fixed some small bugs. need to do some more tests and update the readme.

**Comment by lebaston100** [comment]
Closed with https://github.com/lebaston100/OBSliveTally/commit/d90eaa5bed1773ad44db06ad46075b40ba8abc5f
