### ISSUE TITLE
Page does not update when source/scene is not live anymore

### ISSUE THREAD

**Issue by Melantrix** [lebaston100/OBSliveTally#5]
When i switch from the red page (so when a source or scene is active) to another source that should make the page go black it stay's red and gives the following error in the console:

Uncaught TypeError: Cannot read property 'includes' of undefined
    at OBSliveTally.html:247
    at Array.some (<anonymous>)
    at updateDisplay (OBSliveTally.html:247)
    at handleStateChangeEvent (OBSliveTally.html:236)
    at WebSocket.websocket.onmessage (OBSliveTally.html:61)

**Comment by lebaston100** [comment]
Could you uncomment the console.log in line 56 (https://github.com/lebaston100/OBSliveTally/blob/master/OBSliveTally.html#L56), replicate the error and send me the full console output?

**Comment by Melantrix** [comment]
I did as you asked and tried getting the full output. I've pasted it here: https://pastebin.com/h67ip6cA Because it's syntax got all screwed up behond recognition in this chat. I hope that's what you've asked for, otherwise don't hesitate to ask for more info/logging. 

Do i understand correctly that you cannot reproduce this issue?

**Comment by lebaston100** [comment]
I have not tested it yet myself, but i can see however in the data you provided now that your "Scene 3" seems to be empty (no sources in there). It is possible that this is the issue and is not handled by me correctly. 
Can you just put any source into that scene and try again if you can see any errors happening?
Also if you don't want to mess up the formatting, just screenshot it. That is fine too.

**Comment by Melantrix** [comment]
![chrome_8XNB2yKrlq](https://user-images.githubusercontent.com/4669661/82755896-01167580-9dd7-11ea-9bd6-fb2223d66310.png)

I've put a display source in the empty scene and switched around a few times. Is this what you look for? Here is also the raw log. (i'm an idiot, i just now discovered that you can attach files here..  )
[logging.log](https://github.com/lebaston100/OBSliveTally/files/4673635/logging.log)

**Comment by lebaston100** [comment]
Very interesting. I hope this will be last thing you will have to try. I added a few more debug outputs that should give enough output for me to find the issue: Try again the steps you did last time with the version of the attached zip. Thanks so much for your help.
[OBSliveTally_debug.zip](https://github.com/lebaston100/OBSliveTally/files/4673672/OBSliveTally_debug.zip)

**Comment by Melantrix** [comment]
[logging.log](https://github.com/lebaston100/OBSliveTally/files/4673689/logging.log)

Here is the raw logging, i guess thats sufficient en you don't need a screenshot? If you do, please let me know. 

It's also in my best interest to have this fixed so i'm more then happy to help out! It also helps you respond quite quickly :D

**Comment by lebaston100** [comment]
No problem. I'll try to reproduce it on my side. If i need anything more i'll let you know.
Otherwise i'll get back to you as soon as i have something new.

**Comment by lebaston100** [comment]
Ok, a screenshot would be nice, chrome is really cutting of the important parts  :D
Also just to verify, you are running obs 25.0.8 and obs-websocket 4.7.0?

**Comment by lebaston100** [comment]
Check again with the latest master version.
The problem was that studio mode was never enabled so the "preview scene" field was undefined which lead to that error.
