### ISSUE TITLE
Only green and red screens showing, & Tbar fade breaks app.

### ISSUE THREAD

**Issue by regiside** [lebaston100/OBSliveTally#6]
Wow, Thank you for this incredible application. It was super easy to set up and it's giving me basic needed functionality! I'm running obs and web socket on a mac, and was able to connect using the browser on my iphone. however, I'm seeing to issues: 1. After selecting a scene, the scene never goes black, it just goes green when I move off of that scene regardless of which scene I'm previewing, then when I go live again it returns to red. 2. I know this is a newer feature and I don't even use it at the moment, but I noticed if I touch the new T-bar fader in obs, it seems to totally break the connection in to OBSliveTally. Thanks again for this amazing app!

**Comment by lebaston100** [comment]
I just tried the version from Git. I can't reproduce neither of these issues.
Tested both with Studio Mode Enabled/DIsabled and Source/Scene watching.
Sources go back to Red/Green/Black as they should, T-Bar works fine too.
If you can join the [Discord ](https://discord.gg/PCYQJwX)so we can debug further if you are interested.

**Comment by regiside** [comment]
Oh interesting, Are you on a Mac and iPhone?
  
Maybe I will try another browser on the phone.   
  

  
  

  
  
>

**Comment by lebaston100** [comment]
I am on Windows/Android. Don't have any Apple Hardware to test.
If you can join the [Discord ](https://discord.gg/PCYQJwX)so we can debug further if you are interested.

**Comment by lebaston100** [comment]
I'll close this for now. Feel free to reopen or join the Discord if you have further problems.
