### ISSUE TITLE
[REQUEST] Add support for obs-websocket 5.0 (and OBS 28)

### ISSUE THREAD

**Issue by ameer1234567890** [lebaston100/OBSliveTally#7]
Now that OBS 28 is out and obs-websocket 5.0 is built into OBS, please add support for obs-websocket 5.0. This tool has been of great help in my live streams and I an grateful for that.

**Comment by lebaston100** [comment]
I finished migration for OBS 28 already. It will be pushed to github in a few days. If you want to test already it's available on my discord: [https://discord.gg/PCYQJwX](https://discord.gg/PCYQJwX)

**Comment by ameer1234567890** [comment]
I can confirm that it works perfectly on my OBS 28.0.1 installation.

**Comment by lebaston100** [comment]
Closed with https://github.com/lebaston100/OBSliveTally/commit/09d69dc92cfccd192c0fccc40efbd9970b68cb4d
