### ISSUE TITLE
Manual Selection of RecordingState not showing IDLE or RECORDING.

### ISSUE THREAD

**Issue by KaylonR** [lebaston100/OBSliveTally#8]
Hi there, I found this program for a setup I was hoping to do, but when I was messing around with it, I tried to force set the state to RecordingState, this turns the background red when recording and white when not, but the text doesn't show up at all.

Wondering how this could be fixed?

**Comment by lebaston100** [comment]
As already discussed in the discord, here again for documentation purposes:
Manually changing internal variables is not officially supported and the state save is natively implemented as documented in the readme without having to change source code. I understand the state save currently does not work for you which i can currently not replicate (There will be further debugging in the future on this, but thats a separate issue if it happens to be in my control somehow).
With that being said, automatically loading into the recording watch mode by modifying source code can be achived by replacing https://github.com/lebaston100/OBSliveTally/blob/ee238dced4cd322f1880914b7c2ea7611f59efd9/OBSliveTally.html#L168
with
`await setWatchRecordingStatus();`
